server:
  port: 9000
spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "prod"
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"